# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-Phylo
version:      0.16_RC4
version_from: lib/Bio/Phylo.pm
installdirs:  site
requires:
    Exception::Class:              1.23
    IO::String:                    1.05
    Math::Random:                  0.67
    Scalar::Util:                  0
    SVG:                           1.07
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
