---
abstract: 'An object-oriented Perl toolkit for analyzing and manipulating phyloinformatic data.'
author:
  - 'Rutger Vos'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Phylo
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: https://github.com/rvosa/bio-phylo
  homepage: http://biophylo.blogspot.com/
  repository: git://github.com/rvosa/bio-phylo.git
version: 0.52
