--- #YAML:1.0
name:                Bio-Phylo
version:             0.20
abstract:            ~
license:             ~
author:              
    - Rutger Vos <rvosa@interchange.ubc.ca>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
