# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-Phylo
version:      0.08
version_from: lib/Bio/Phylo.pm
installdirs:  site
requires:
    base:                          0
    Exception::Class:              0
    fields:                        0
    Hash::Util:                    0
    IO::String:                    0
    Math::Random:                  0
    Scalar::Util:                  0
    Storable:                      0
    SVG:                           1.07
    Test::More:                    0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
